server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management_system
    username: root
    password: Mukul@2105
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret: QfTjWnZq4t7w!z%C*F-JaNdRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H
  expiry: 5
